HOSTING_ASN_KEYWORDS = [  
  'hosting',
  'aldiyanur mahakam telemedia',
  'andhika pratama sanggoro',
  'ardh global indonesia',
  'atharva telematika persada',
  'awan data teknologi',
  'awan media semesta',
  'beon intermedia',
  'berkah solusi teknologi informasi',
  'cepat multi data',
  'cloud hosting indonesia',
  'cyberzone',
  'data digital indotama',
  'delta neva angkasa',
  'deneva',
  'dewa bisnis digital',
  'dewaweb',
  'delta awan angkasa',
  'exabytes',
  'foura inti sinergi',
  'gunung sedayu sentosa',
  'herza digital indonesia',
  'hostinger',
  'industri kreatif digital',
  'informasi nusantara teknologi',
  'internet company llp',
  'intercloud digital inovasi',
  'jaringan lintas artha',
  'master web network',
  'media antar nusa',
  'mora telematika indonesia',
  'parsaoran global datatrans',
  'raja mitra informatika',
  'registrasi neva angkasa',
  'rumahweb',
  'selaras citra terabit',
  'trisari data indonusa',
  'webico',
  'cloud host',
  'microsoft corporation',
  'digitalocean',
  'amazon.com',
  'huawei clouds',
  'akamai',
  'linode',
  'ovh',
  'uab host',
  'driftnet',
  'speedypage',
  'babbar',
  'contabo',
  'dromatics',
  'dm auto eood',
  'vultr',
  'hosting plus',
  'hostpapa',
  'qwarta',
  'ionos',
  'ip volume',
  'isaev igor',
  'hetzner',
  '3xk',
  'drei-k-tech',
  'detai prosperous',
  'leaseweb',
  'm247',
  'onyphe sas',
  'scaleway',
  'services ab',
  'the constant',
  'ghosty networks',
  'ucloud information technology',
  'telchak gold ventures',
  'kamatera',
  'netcup',
  'next layer',
  'clouvider',
  'censys',
  'gsl',
  'jsc',
  'cheapy',
  'choopa',
  'sovy',
  'serverastra',
  'oracle',
  'carvalho',
  'chinanet-backbone',
  'colocatel',
  'advin',
  'alsycon',
  'railnet',
  'de-corp',
  'delska',
  'dzcrd',
  'xneelo',
  'angkor data communication',
  'hkbn enterprise solutions',
  'bucklog',
  'code200',
  'datacamp',
  'dpkgsoft',
  'en technologies',
  'enzu',
  'f.n.s.',
  'gthost',
  'hosthatch',
  'nexet',
  'nsec',
  'ufinet',
  'china169',
  'hurricane electric',
  'redheberg association declaree',
  'tencent building',
  'tencent computer',
  'trafficforce',
  'unmanaged ltd',
  'galeon',
  'kaopu',
  'mevspace',
  'nls kazakhstan',
  'trulo',
  'packethub',
  'pfcloud',
  'servervia',
  'techoff',
  'unifet',
  'velia.net',
  'yandex.cloud',
  'yisu cloud',
  'worldstream',
  'wowrack'
]
