HOSTING_ASN_KEYWORDS = [  
  'hosting',
  'aldiyanur mahakam telemedia',
  'andhika pratama sanggoro',
  'ardh global indonesia',
  'awan data teknologi',
  'awan media semesta',
  'beon intermedia',
  'berkah solusi teknologi informasi',
  'cepat multi data',
  'cloud hosting indonesia',
  'cyberzone',
  'delta neva angkasa',
  'deneva',
  'dewa bisnis digital',
  'dewaweb',
  'delta awan angkasa',
  'exabytes',
  'foura inti sinergi',
  'gunung sedayu sentosa',
  'herza digital indonesia',
  'hostinger',
  'industri kreatif digital',
  'informasi nusantara teknologi',
  'internet company llp',
  'intercloud digital inovasi',
  'jaringan lintas artha',
  'master web network',
  'media antar nusa',
  'mora telematika indonesia',
  'parsaoran global datatrans',
  'raja mitra informatika',
  'registrasi neva angkasa',
  'rumahweb',
  'selaras citra terabit',
  'trisari data indonusa',
  'webico',
  'cloud host',
  'microsoft corporation',
  'digitalocean',
  'amazon.com',
  'huawei clouds',
  'akamai',
  'linode',
  'ovh',
  'speedypage',
  'contabo',
  'dromatics',
  'vultr',
  'hosting plus',
  'hostpapa',
  'qwarta',
  'ionos',
  'hetzner',
  '3xk',
  'drei-k-tech',
  'leaseweb',
  'm247',
  'scaleway',
  'services ab',
  'the constant',
  'telchak gold ventures',
  'kamatera',
  'netcup',
  'clouvider',
  'gsl',
  'jsc',
  'cheapy',
  'choopa',
  'sovy',
  'serverastra',
  'oracle',
  'carvalho',
  'chinanet-backbone',
  'colocatel',
  'advin',
  'alsycon',
  'railnet',
  'delska',
  'dzcrd',
  'xneelo',
  'code200',
  'datacamp',
  'en technologies',
  'f.n.s.',
  'gthost',
  'hosthatch',
  'nsec',
  'china169',
  'tencent building',
  'tencent computer',
  'trafficforce',
  'unmanaged ltd',
  'galeon',
  'kaopu',
  'trulo',
  'pfcloud',
  'unifet',
  'dpkgsoft',
  'velia.net',
  'yisu cloud',
  'worldstream',
  'wowrack'
]
